routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\ProductsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('test_middlewate')->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

// Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('/', [CategoriesController::class, 'index'])->name('index');
        Route::get('/create', [CategoriesController::class, 'create'])->name('create');
        Route::post('/store', [CategoriesController::class, 'store'])->name('store');
        Route::get('/{id}', [CategoriesController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [CategoriesController::class, 'edit'])->name('edit');
        Route::put('/{id}', [CategoriesController::class, 'edit'])->name('update');
        Route::delete('/{id}', [CategoriesController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', [ProductsController::class, 'index'])->name('index');
        Route::get('/create', [ProductsController::class, 'create'])->name('create');
        Route::post('/', [ProductsController::class, 'store'])->name('store');
        Route::get('/{id}', [ProductsController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [ProductsController::class, 'edit'])->name('edit');
        Route::put('/{id}', [ProductsController::class, 'update'])->name('update');
        Route::delete('/{id}', [ProductsController::class, 'destroy'])->name('destroy');
    });
// });

// Route::resources([
//     'category' => CategoriesController::class,
// ]);


// ->middleware('test_middlewate')

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CategoriesRequest;
use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class CategoriesController extends Controller
{
    private $category;
    /**
     * Construct
    */
    public function __construct(Categories $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {
        $data = [];
        
        // $categories = DB::select('select * from categories');

        $categories = $this->category;

        // Check have Search ?
        if ($request->name) {
            $categories = $categories->where('name', 'like', '%' . $request->name . '%');
        }

        // $categories = $categories->count('name');

        $categories = $categories->get();
        
        $data['categories'] = $categories; 
        // dd($data);

        return view('categories.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        return view('categories.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriesRequest $request)
    {
        $categoryInsert = [
            'name' => $request->category_name
        ];

        try {
            // insert into data to table category (successful)
            $this->category->create($categoryInsert);
            return redirect()->route('category.index')->with('success', trans('message.store_category_success'));

        } catch (\Exception $ex) {
            //insert into data to table category (fail)
            Log::error($ex->getMessage());
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show(Categories $categories)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];
        $category = $this->category->findOrFail($id);
        $data['category'] = $category;

        return view('categories.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriesRequest $request, $id)
    {
        try {
            $category = $this->category->findOrFail($id);

            $category->name = $request->category_name;
            $category->save();

            return redirect()->route('category.index')->with('success', trans('message.update_category_success'));
        } catch (\Exception $ex) {
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $category = $this->category->find($id);
            $category->delete();
            return redirect()->route('category.index')->with('success', trans('message.delete_category_success'));
        } catch (\Exception $ex) {
            return redirect()->back()->with('error', $ex->getMessage());
        }
        
    }
}

resources/views/categories/_search.blade.php
<div class="d-flex justify-content-between mb-3">
    <div>
        {{-- create category link --}}
        <a href="{{ route('category.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> {{ __('message.create') }}</a>

        {{-- @if(!$categories->isEmpty())
            {{ __('message.display_total_record', ['total' => $categories->count()]) }}
        @endif --}}
    </div>
    <div>
        <form action="{{ route('category.index') }}" method="get">
            <input type="text" placeholder="" name="name" value="{{ request()->name }}" class="form-control-custom d-inline-block">
            <button type="submit" class="btn btn-primary d-inline-block"><i class="fas fa-search"></i> {{ __('message.search') }}</button>
        </form>
    </div>
</div>

resources/views/categories/create.blade.php
@extends('layouts.master')

{{-- set page title --}}
@section('title', __('message.create_category'))

{{-- import file css (private) --}}

@section('content')
    <form action="{{ route('category.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="" class="required">{{ __('message.category_name') }}</label>
                    <input type="text" name="category_name" class="form-control">
                    @error('category_name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>

        <p><span class="red">(*)</span>: {{ __('message.required') }}</p>

        <div class="form-group">
            <a href="{{ route('category.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('message.category_list') }}</span></a>
            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> <span class="ml-2">{{ __('message.save') }}</span></button>
        </div>
    </form>
@endsection

resources/views/categories/detail.blade.php
<p>Detail Category</p>

resources/views/categories/edit.blade.php
@extends('layouts.master')

{{-- set page title --}}
@section('title', __('message.edit_category'))

@section('content')
    <form action="{{ route('category.update', $category->id) }}" method="post">
        @csrf
        @method('PUT')

        <div class="form-group mb-3">
            <div class="row">
                <div class="col-md-4">
                    <label for="" class="required">{{ __('message.category_name') }}</label>
                    <input type="text" name="category_name" value="{{ old('category_name', $category->name) }}" class="form-control">
                    @error('category_name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>
        
        <p><span class="red">(*)</span> {{ __('message.required') }}</p>

        <div class="form-group">
            <a href="{{ route('category.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('message.category_list') }}</span></a>
            <button type="submit" class="btn btn-primary"><i class="far fa-edit"></i> <span class="ml-2">{{ __('message.update') }}</span></button>
        </div>
    </form>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.master')

@section('title', __('message.category_list'))

@section('content')
    @include('categories._search')

        {{-- show message --}}
    @if(Session::has('success'))
        <p class="text-success">{{ Session::get('success') }}</p>
    @endif

    {{-- show error message --}}
    @if(Session::has('error'))
        <p class="text-danger">{{ Session::get('error') }}</p>
    @endif

    {{-- display list category table --}}

    @if ($categories->isEmpty())
        <p class="red">{{ __('message.not_found_data') }}</p>
    @else
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th>{{ __('message.category_name') }}</th>
                {{-- <th>{{ __('message.product_list') }}</th> --}}
                <th colspan="2">{{ __('message.action') }}</th>

            </tr>
            </thead>
            <tbody>
                @foreach ($categories as $key => $item)
                    <tr>
                        <th scope="row">{{ $key+1 }}</th>
                        <td>{{ $item->name }}</td>
                        <td>
                            <a href="{{ route('category.edit', $item->id) }}">
                                <button type="button" class="btn btn-warning">{{ __('message.edit') }}</button>
                        </td>
                        <td>       
                                                
                            <form action="{{ route('category.destroy', $item->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-common" onclick="return confirm('{{ __('message.confirm_delete') }}')"><i class="fas fa-trash-alt"></i> {{ __('message.delete') }}</button>
                            </form>
                        </td>
                    </tr>      
                    
                @endforeach
            </tbody>
        </table>
    @endif

@endsection