routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\ProductsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('test_middlewate')->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/contact', function () {
    return view('contact');
})->name('contact');

// Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('/', [CategoriesController::class, 'index'])->name('index');
        Route::get('/create', [CategoriesController::class, 'create'])->name('create');
        Route::post('/store', [CategoriesController::class, 'store'])->name('store');
        Route::get('/{id}', [CategoriesController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [CategoriesController::class, 'edit'])->name('edit');
        Route::put('/{id}', [CategoriesController::class, 'edit'])->name('update');
        Route::delete('/{id}', [CategoriesController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('/', [ProductsController::class, 'index'])->name('index');
        Route::get('/create', [ProductsController::class, 'create'])->name('create');
        Route::post('/', [ProductsController::class, 'store'])->name('store');
        Route::get('/{id}', [ProductsController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [ProductsController::class, 'edit'])->name('edit');
        Route::put('/{id}', [ProductsController::class, 'update'])->name('update');
        Route::delete('/{id}', [ProductsController::class, 'destroy'])->name('destroy');
    });
// });

// Route::resources([
//     'category' => CategoriesController::class,
// ]);


// ->middleware('test_middlewate')

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Products extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $table = 'products';

    protected $fillable = [

        'category_id',
        'name',
        'thumbnail',
        'description',
        'content',
        'status',
        'quantily',
        'price',
        'images',
    ];

    public $timestamps = true;

    // protected $hidden = [

    // ];

    // public const STATUS = [
    //     0,  //hidden
    //     1, //show
    // ];

    // public const PAGE_LIMIT = 10;

    /**
     * Get the category that owns the post.
     */
    public function category()
    {
        return $this->belongsTo(Categories::class, 'category_id', 'id');
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\ProductRequest;
use App\Models\Categories;
use App\Models\Products;
use App\Utils\UploadFile;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    private $folderThumb;
    private $folderImage;
    protected $product;
    protected $category;

    public function __construct(Products $product, Categories $category)
    {
        $this->category = $category;
        $this->product = $product;

        // Set Path for folder Upload File
        $this->folderThumb = config('common.folder_product_thumb_upload');
        $this->folderImage = config('common.folder_product_img_upload');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = [];

        // Set Sort Data
        $orderBy = $request->get('order_by', 'id');
        $sortedBy = $request->get('sorted_by', 'desc');

        // Set Pagiantion Limit in per page
        $perPage = $request->get('per_page', config('common.pagination_limit_10'));

        // Set Field List
        $fields = [
            'products.category_id',
            'categories.name as category_name',
            'products.id',
            'products.name',
            'products.thumbnail',
            'products.price',
        ];

        // Get list data of table products
        $products = $this->product
            ->select($fields)
            ->leftJoin('categories', 'products.category_id', '=', 'categories.id');

        // Search with keyword
        if (!empty($request->keyword)) {
            $products = $products->where('products.name', 'like', '%' . $request->keyword . '%');
        }

        // Search category_id
        if (!empty($request->category_id)) {
            $products = $products->where('products.category_id', $request->category_id);
        }

        // Sort Data
        $products = $products->orderBy($orderBy, $sortedBy);

        // Pagination
        $products = $products->paginate($perPage);
        $data['products'] = $products;

        // Get list data of table categories
        $categories = $this->category->pluck('name', 'id')
            ->toArray();
        $data['categories'] = $categories;
        return view('products.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];

        // Get Category List
        $categories = $this->category->pluck('name', 'id')
            ->toArray();
        $data['categories'] = $categories;

        return view('products.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        // Upload Thumbnail
        $thumbnailPath = UploadFile::upload($request->thumbnail, $this->folderThumb);

        // Upload Images
        $files = $request->images;
        $productImages = UploadFile::upload($files, $this->folderImage);
        $productImages = empty($productImages) ? [] : $productImages;

        // Define Variable
        $dataInsert = [
            'name' => $request->name,
            'thumbnail' => $thumbnailPath,
            'description' => $request->description,
            'content' => $request->content,
            'quantity' => $request->quantity,
            'price' => $request->price,
            'images' => json_encode($productImages),
            'category_id' => $request->category_id,
        ];

        try {
            // insert into table products
            $this->product->create($dataInsert);

            // success
            return redirect()->route('products.index')
                ->with('success', 'Insert successful!');
        } catch (\Exception $ex) {
            return redirect()->back()
                ->with('error', $ex->getMessage())
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Define Variable
        $data = [];

        // Get Product Detail
        $product = $this->product
            ->findOrFail($id);
        $data['product'] = $product;

        return view('products.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];

        // Get Product Detail
        $product = $this->product
            ->findOrFail($id);
        $data['product'] = $product;

        // Get Category List
        $categories = $this->category->pluck('name', 'id')
            ->toArray();
        $data['categories'] = $categories;

        return view('products.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Products $products)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Products  $products
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Get Product
        $product = $this->product
            ->findOrFail($id);

        try {
            // delete data of table products
            $product->delete();

            // success
            return redirect()->route('products.index')
                ->with('success', 'Delete successful!');
        } catch (\Exception $ex) {
            return redirect()->back()
                ->with('error', $ex->getMessage());
        }
    }
}

resources/views/products/__table_head.blade.php
@php
// Sort Product Name (Desc)
$sortProductNameDesc = [
    'order_by' => 'name',
    'sorted_by' => 'desc',
];

// Sort Product Name (Asc)
$sortProductNameAsc = [
    'order_by' => 'name',
    'sorted_by' => 'asc',
];
@endphp

<thead class="bg-info">
    <tr>
        <th class="text-center">#</th>
        <th>{{ __('message.product_name') }}
            <div class="d-inline-block">
                <div class="control-sort">
                    @if(request()->order_by == 'name' && request()->sorted_by == 'asc')
                        <a href="{{ route('products.index', array_merge($paramRequest, $sortProductNameDesc)) }}"><i class="fas fa-sort-down"></i></a>
                    @elseif(request()->order_by == 'name' && request()->sorted_by == 'desc')
                        <a href="{{ route('products.index', array_merge($paramRequest, $sortProductNameAsc)) }}"><i class="fas fa-sort-up"></i></a>
                    @else
                        <a href="{{ route('products.index', array_merge($paramRequest, $sortProductNameAsc)) }}"><i class="fas fa-sort-up"></i></a>
                        <a href="{{ route('products.index', array_merge($paramRequest, $sortProductNameDesc)) }}"><i class="fas fa-sort-down"></i></a>
                    @endif
                </div>
            </div>
        </th>
        <th>{{ __('message.thumbnail') }}</th>
        <th>{{ __('message.price') }}</th>
        <th>{{ __('message.category_name') }}</th>
        <th colspan="4">{{ __('message.action') }}</th>
    </tr>
</thead>

resources/views/products/_search.blade.php
@php
    $categorySearch = request()->get('category_id') ? request()->get('category_id') : null;
@endphp

<!-- SHARING -->
<!-- jQuery Plugin Select2: https://select2.github.io/select2/ -->

<div class="mb-5 border p-3 bg-white section-search">
    <form action="{{ route('products.index') }}" method="GET" id="frm-product-search">
        <input type="hidden" name="per_page" value="10" id="per-page">
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">{{ __('message.keyword') }}</label>
                    <input type="text" class="form-control" name="keyword" placeholder="{{ __('message.keyword_product_search_ph') }}" value="{{ request()->get('keyword') }}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">{{ __('message.category') }}</label>
                    <select name="category_id" class="form-control category-select2">
                        <option value=""></option>
                        @if(!empty($categories))
                            @foreach ($categories as $categoryId => $categoryName)
                                <option value="{{ $categoryId }}" {{ $categoryId == $categorySearch ? 'selected' : ''  }}>{{ $categoryName }}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
            </div>
        </div>
    
        <p>
            <button type="button" class="btn btn-secondary" onclick="window.location.href='{{ route('products.index') }}'"><i class="fas fa-sync-alt"></i> {{ __('message.reset') }}</button>
            <button type="submit" class="btn btn-primary" title="{{ __('message.search_product') }}"><i class="fas fa-search"></i> {{ __('message.search') }}</button>
        </p>
    </form>
</div>

resources/views/products/_table.blade.php
@if($products->isEmpty())
    {{-- create product link --}}
    <div class="d-inline-block mb-2"><a href="{{ route('products.create') }}" class="btn btn-primary" title="{{ __('message.create_product') }}"><i class="fas fa-plus"></i> {{ __('message.create') }}</a></div>
    
    <p class="red">{{ __('message.not_found_data') }}</p>
@else
    <div class="d-flex justify-content-between">
        <div class="">
            {{-- create product link --}}
            <div class="d-inline-block"><a href="{{ route('products.create') }}" class="btn btn-primary" title="{{ __('message.create_product') }}"><i class="fas fa-plus"></i> {{ __('message.create') }}</a></div>
            
            <!-- Set Limit Record in Per Page -->
            <select name="per_page" onChange="submitFilterProduct(this)" class="d-inline-block ml-2 form-control-custom">
                <option value="10" {{ request()->per_page == 10 ? 'selected' : '' }}>10</option>
                <option value="50" {{ request()->per_page == 50 ? 'selected' : '' }}>50</option>
                <option value="100" {{ request()->per_page == 100 ? 'selected' : '' }}>100</option>
                <option value="200" {{ request()->per_page == 200 ? 'selected' : '' }}>200</option>
            </select>&nbsp;
            <label for="">{{ __('message.record_per_page') }}</label>
        </div>
        <div>
            {{ $products->appends(request()->input())->links() }}
        </div>
    </div>

    <table id="product-list" class="table table-bordered table-hover table-striped">
        @include('products.__table_head')
        <tbody>
            @if(!empty($products))
                @foreach ($products as $key => $product)
                    <tr>
                        <td class="text-center">{{ $key+1 }}</td>
                        <td>{{ $product->name }} (<span class="font-weight-bold">{{ $product->order_detail_count }} {{ __('message.order') }}</span>)</td>
                        <td>
                            <img src="{{ asset($product->thumbnail) }}" alt="{{ $product->name }}" class="img-fluid" style="width: 240px; height: auto;">
                        </td>
                        <td>{{ $product->price }}</td>
                        <td>{{ $product->category_name }}</td>
                        <td><a href="{{ route('products.show', $product->id) }}" class="btn btn-secondary btn-common" title="{{ __('message.detail_product') }}"><i class="fas fa-search-plus"></i> {{ __('message.detail') }}</a></td>
                        <td><a href="{{ route('products.edit', $product->id) }}" class="btn btn-info btn-common" title="{{ __('message.edit_product') }}"><i class="fas fa-edit"></i> {{ __('message.edit') }}</a></td>
                        <td>
                            @if($product->order_detail_count && $product->order_detail_count > 0)
                                <button type="button" class="btn btn-danger btn-common" disabled><i class="fas fa-trash-alt"></i> {{ __('message.delete') }}</button>
                            @else
                                <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-common" onclick="return confirm('{{ __('message.confirm_delete_product') }}')" title="{{ __('message.delete_product') }}"><i class="fas fa-trash-alt"></i> {{ __('message.delete') }}</button>
                                </form>
                            @endif
                        </td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>

    <div class="d-flex justify-content-between">
        <div>
            @php
                $currentPage = $products->currentPage() - 1;
                $perPage = $products->perPage();
                $total = $products->total();
                $from = ($currentPage * $perPage) + 1;
                $to = ($currentPage * $perPage) + $perPage;
            @endphp
            {{ __('message.show_per_page', ['from' => $from, 'to' => $to, 'total' => $total]) }}
        </div>
        <div class="">
            {{ $products->appends(request()->input())->links() }}
        </div>
    </div>
@endif

resources/views/products/create.blade.php
@extends('layouts.master')

{{-- set page title --}}
@section('title', __('message.create_product'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('message.product_management'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.create_product'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/css/product.css">
@endpush

{{-- import file js (private) --}}
@push('js')
    <!-- add jquery custom -->
    <script src="/js/product.js"></script>
@endpush

@section('content')
    <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col-md-6">
                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.product_name') }}</label>
                    <input type="text" name="name" placeholder="" value="{{ old('name') }}" class="form-control">
                    @error('name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.thumbnail') }}</label><br>
                    <input type="file" name="thumbnail" class="form-control">
                    @error('thumbnail')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.quantity') }}</label>
                    <input type="text" name="quantity" placeholder="" value="{{ old('quantity') }}" class="form-control">
                    @error('quantity')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.category') }}</label>
                    <select name="category_id" class="form-control">
                        <option value=""></option>
                        @if(!empty($categories))
                            @foreach ($categories as $categoryId => $categoryName)
                                <option value="{{ $categoryId }}" {{ old('category_id') == $categoryId ? 'selected' : ''  }}>{{ $categoryName }}</option>
                            @endforeach
                        @endif
                    </select>
                    @error('category_id')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="">{{ __('message.product_image') }}</label><br>
                    <input type="file" name="images[]" multiple>
                    @error('url')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.price') }}</label>
                    @php
                        // Define Variable
                        $price = null;

                        // Check Old Data
                        if (old('price')) {
                            // Get Value of Price
                            $price = old('price');
    
                            // Remove Character Special
                            $price = \App\Utils\CommonUtil::removeCharSpecPrice($price);
    
                            // Format
                            $price = empty($price) ? null : number_format($price, 2);
                        }
                    @endphp
                    <input type="text" name="price" placeholder="" value="{{ $price }}" class="form-control" id="price">
                    @error('price')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>

        <div class="form-group mb-5">
            <label for="" class="required">{{ __('message.product_description') }}</label>
            <textarea name="description" rows="2" class="form-control">{{ old('description') }}</textarea>
            @error('description')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="form-group mb-5">
            <label for="" class="required">{{ __('message.product_content') }}</label>
            <textarea name="content" rows="10" class="form-control">{{ old('content') }}</textarea>
            @error('content')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>

        <p><span class="red">(*)</span>: {{ __('message.required') }}</p>

        <div class="form-group">
            <a href="{{ route('products.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('message.product_list') }}</span></a>
            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> <span class="ml-2">{{ __('message.save') }}</span></button>
        </div>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.master')

{{-- set page title --}}
@section('title', __('message.edit_product'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('message.product_management'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.edit_product'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/css/product.css">
@endpush

{{-- import file js (private) --}}
@push('js')
    <!-- add jquery custom -->
    <script src="/js/product.js"></script>
@endpush

@section('content')    
    <form action="{{ route('products.update', request()->route('id')) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="row">
            <div class="col-md-6">
                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.product_name') }}</label>
                    <input type="text" name="name" placeholder="" value="{{ old('name', $product->name) }}" class="form-control">
                    @error('name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.thumbnail') }}</label><br>
                    <img src="{{ asset($product->thumbnail) }}" alt="{{ $product->name }}" class="img-fluid">
                    <input type="file" name="thumbnail" class="form-control">
                    @error('thumbnail')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.quantity') }}</label>
                    <input type="text" name="quantity" placeholder="" value="{{ old('quantity', $product->quantity) }}" class="form-control">
                    @error('quantity')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.category') }}</label>
                    <select name="category_id" class="form-control">
                        <option value=""></option>
                        @if(!empty($categories))
                            @foreach ($categories as $categoryId => $categoryName)
                                <option value="{{ $categoryId }}" {{ old('category_id', $product->category_id) == $categoryId ? 'selected' : ''  }}>{{ $categoryName }}</option>
                            @endforeach
                        @endif
                    </select>
                    @error('category_id')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="">{{ __('message.product_image') }}</label>
                    <input type="file" name="images[]" multiple class="form-control">

                    {{-- show all image of table product_images --}}
                    @if (!empty($product->images))
                        <ul class="row list-product-image">
                            @foreach ($product->images as $image)
                                <li class="col-4">
                                    <div class="product-image-group">
                                        <img src="{{ asset($image) }}" alt="image" class="img-fluid">
                                        <input type="hidden" name="old_images[]" value="{{ $image }}">
                                        <button type="button" class="btn btn-danger form-control mt-1" onclick="$(this).closest('li').remove()">Remove Image</button>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    @endif

                    @error('images')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group mb-5">
                    <label for="" class="required">{{ __('message.price') }}</label>
                    @php
                        // Get Value of Price
                        $price = old('price', $product->price);

                        // Remove Character Special
                        $price = \App\Utils\CommonUtil::removeCharSpecPrice($price);

                        // Format
                        $price = empty($price) ? null : number_format($price, 2);
                    @endphp
                    <input type="text" name="price" placeholder="" value="{{ $price }}" class="form-control" id="price">
                    @error('price')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>

        <div class="form-group mb-5">
            <label for="" class="required">{{ __('message.product_description') }}</label>
            <textarea name="description" rows="2" class="form-control">{{ old('description', $product->description) }}</textarea>
            @error('description')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="form-group mb-5">
            <label for="" class="required">{{ __('message.product_content') }}</label>
            <textarea name="content" rows="10" class="form-control">{{ old('content', $product->content) }}</textarea>
            @error('content')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>

        <p><span class="red">(*)</span> {{ __('message.required') }}</p>

        <div class="form-group">
            <a href="{{ route('products.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('message.product_list') }}</span></a>
            <button type="submit" class="btn btn-primary"><i class="far fa-edit"></i> <span class="ml-2">{{ __('message.update') }}</span></button>
        </div>
    </form>
@endsection

resources/views/products/index.blade.php
@php
    // Get Param Request
    $paramRequest = request()->except('page');
@endphp

@extends('layouts.master')

{{-- set page title --}}
@section('title', __('message.product_list'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('message.product_management'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.product_list'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/css/product.css">
@endpush

{{-- import file js (private) --}}
@push('js')
    <!-- add jquery custom -->
    <script src="/js/product.js"></script>
@endpush

@section('content')
    {{-- show message --}}
    @if(Session::has('success'))
        <p class="text-success">{{ Session::get('success') }}</p>
    @endif

    {{-- show error message --}}
    @if(Session::has('error'))
        <p class="text-danger">{{ Session::get('error') }}</p>
    @endif

    {{-- form search --}}
    @include('products._search')

    {{-- display list product table --}}
    @include('products._table')
@endsection